version: "3.9"

services:
  app:
    #image: node:22
    build: .
    container_name: node_app
    working_dir: /usr/src/app
    
    #volumes:
     # - .:/usr/src/app:cached
    volumes:
      - .:/usr/src/app:cached
    

     

     
    ports:
      - "3000:3000"
    depends_on:
       db:
        condition: service_healthy
    # command: node server.js
    # command: npx ts-node server.ts
    command: node dist/server.js
    environment:
       DB_USER: root
       DB_PASS: rootpass
       DB_HOST: db
       DB_PORT: 3306
       DB_NAME: sampledb
  
    
    env_file:
      - .env
    
       

    
       
  
  db:
    image: mysql:8.0
    environment:
       MYSQL_ROOT_PASSWORD: rootpass
       MYSQL_DATABASE: sampledb
       MYSQL_USER: user
       MYSQL_PASSWORD: pass

    ports:
       - "3306:3306" 

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1s
      timeout: 5s
      retries: 5


    volumes:
      - db_data:/var/lib/mysql
        

volumes:
  db_data:


